language: java

jdk:
  - oraclejdk8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/388dcf6313190124f315
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file:
    - "/home/travis/.m2/repository/com/containersolutions/mesos/mesos-starter/$TRAVIS_TAG/mesos-starter-$TRAVIS_TAG.pom"
    - "/home/travis/.m2/repository/com/containersolutions/mesos/mesos-starter/$TRAVIS_TAG/mesos-starter-$TRAVIS_TAG.pom.sha1"
    - "/home/travis/.m2/repository/com/containersolutions/mesos/spring-boot-starter-mesos/$TRAVIS_TAG/spring-boot-starter-mesos-$TRAVIS_TAG.jar"
    - "/home/travis/.m2/repository/com/containersolutions/mesos/spring-boot-starter-mesos/$TRAVIS_TAG/spring-boot-starter-mesos-$TRAVIS_TAG.jar.sha1"
    - "/home/travis/.m2/repository/com/containersolutions/mesos/spring-boot-starter-mesos/$TRAVIS_TAG/spring-boot-starter-mesos-$TRAVIS_TAG-javadoc.jar"
    - "/home/travis/.m2/repository/com/containersolutions/mesos/spring-boot-starter-mesos/$TRAVIS_TAG/spring-boot-starter-mesos-$TRAVIS_TAG-javadoc.jar.sha1"
    - "/home/travis/.m2/repository/com/containersolutions/mesos/spring-boot-starter-mesos/$TRAVIS_TAG/spring-boot-starter-mesos-$TRAVIS_TAG-sources.jar"
    - "/home/travis/.m2/repository/com/containersolutions/mesos/spring-boot-starter-mesos/$TRAVIS_TAG/spring-boot-starter-mesos-$TRAVIS_TAG-sources.jar.sha1"
    - "/home/travis/.m2/repository/com/containersolutions/mesos/spring-boot-starter-mesos/$TRAVIS_TAG/spring-boot-starter-mesos-$TRAVIS_TAG.pom"
    - "/home/travis/.m2/repository/com/containersolutions/mesos/spring-boot-starter-mesos/$TRAVIS_TAG/spring-boot-starter-mesos-$TRAVIS_TAG.pom.sha1"
  skip_cleanup: true
  on:
    tags: true
