spring:
  application:
    name: Sample App

mesos:
  tasks:
    - name: server
      command: nc -l ${SERVER_PORT}
      docker:
        image: alpine
      resources:
        count: 1
        cpus: 0.1
        mem: 64
        ports:
          server-port:
            host: 31101
            container: 80
    - name: slave
      command: sleep 200
      docker:
        image: alpine
      resources:
        count: 1
        cpus: 0.1
        mem: 64
