spring:
  application:
    name: Sample App

mesos:
  command: sleep 60
  resources:
#    distinctSlave: true
    count: 1
    cpus: 0.01
    mem: 4
    docker:
#    image: tutum/hello-world:latest
    image: alpine
