spring:
  application:
    name: Sample App

mesos:
  command: sleep 600
  resources:
    distinctSlave: true
    scale: 1
    cpus: 0.1
    mem: 64
#    ports:
#      nc-port:
#        host: 31101
#        container: 80
#    volumes:
#      - hostPath: /etc
#        containerPath: /hostetc
  docker:
#    image: tutum/hello-world:latest
    image: alpine
